[project]
name = "msc-thesis-code"
version = "0.1.0"
description = "MSc Thesis Code"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.5",
]

[tool.marimo.experimental]
lsp = true

[tool.marimo.diagnostics]
enabled = true
